image: node:latest

pages:
  stage: deploy
  script:
    - npm install
    - npm run build:prod
    - npm run webpack
    - mkdir public
    - mv demo/* public
  artifacts:
    paths:
    - public
  only:
  - master