image: node:latest

pages:
  stage: deploy
  script:
<<<<<<< HEAD
    - npm install
    - npm run build:prod
=======
>>>>>>> parent of e6a2f08... update gitlab-ci
    - npm run webpack
  artifacts:
    paths:
    - demo
  only:
  - master